services:
  mysql:
    image: mysql:latest
    container_name: mysql_containerci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ci
      MYSQL_USER: ci
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_dataci:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_containerci
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - app-network
volumes:
  mysql_dataci:
networks:
  app-network:
    driver: bridge
